### ISSUE TITLE
Normalized Output

### ISSUE THREAD

**Issue by mbernico** [mbernico/snape#1]
Currently artificial datasets are generated as flat csv files.  Datasets could be made more realistic by artificially normalizing them into multiple tables, requiring students to create joins for denormalization.   

This should be an optional parameter.

**Comment by scollins83** [comment]
Currently developing the first step of this in the 'star_schema_csv' branch.

**Comment by scollins83** [comment]
Question--- as to updating the 'Doc' folder, should I do that manually, or did you generate the markdown files?

**Comment by mbernico** [comment]
@scollins83  Can you check to see if you were invited as a contributor?  If so, accept so I can assign this to you and you can be internet famous!

Doc file is hand generated.

**Comment by scollins83** [comment]
Ok, went back and found that email :-)

**Comment by mbernico** [comment]
Thank you!   I'm sorry I still haven't gotten to your PR, I'll get there soon.

**Comment by mbernico** [comment]
@scollins83 addressed in pr #5
