### ISSUE TITLE
as a researcher, I want to be able to easily reproduce results

### ISSUE THREAD

**Issue by mbernico** [mbernico/snape#6]
add random seed to json configuration so a researcher can publish their json file for reproducible research.

**Comment by mbernico** [comment]
[Like this](https://github.com/tgsmith61591/smrt/blob/master/smrt/utils.py#L20)

**Comment by tgsmith61591** [comment]
This was fixed in 8dfe0d9. Once merged, make sure to close this out, @mbernico

**Comment by mbernico** [comment]
Resolved in PR #9    Thanks @tgsmith61591
